#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InfApp.Resource", IsApplication=true)]

namespace InfApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int theme_custom_background = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int curvedButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int EditTextItemID = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int EditTextItemName = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int EditTextItemQuantity = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int InToMain = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int ItemAccountAux = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int ItemAccountAuxText = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int ItemIdText = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int ItemNameText = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int ItemPriceTotal = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int ItemPriceTotalText = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int ItemPriceUnit = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int ItemPriceUnitText = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int ItemQuantityText = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int MainToInButton = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int MainToPickButton = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int MainToRelocateButton = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int MainToToFactButton = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int ScrollView01 = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int space1 = 2131165204;
			
			// aapt resource value: 0x7f07000f
			public const int textView1 = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int InMainWindow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int InTitle = 2130968578;
			
			// aapt resource value: 0x7f040011
			public const int ItemAccountAux = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int ItemAccountAuxText = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int ItemId = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int ItemIdText = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int ItemName = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int ItemNameText = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int ItemPriceTotal = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int ItemPriceTotalText = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int ItemPriceUnit = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int ItemPriceUnitText = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int ItemQuantity = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int ItemQuantityText = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int PickTitle = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int RelocationTitle = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ToFactTitle = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Custom1 = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
